require("plugins/neo-tree-nvim")
require("plugins/telescope-nvim")
require("plugins/nvim-comment")
require("plugins/mini-nvim")
require("plugins/treesitter-nvim")
require("plugins/gitsigns-nvim")
require("plugins/nvim-scrollbar")
require("plugins/nvim-colorizer")
require("plugins/nvim-spectre")
require("plugins/nvim-hlslens")
require("plugins/vim-tmux-navigator")
require("plugins/nvim-ufo")
-- require("plugins/lualine-nvim")
require("plugins/bufferline-nvim")
require("plugins/nvim-lightbulb")
